# 12.2.1 张量和操作

## 使用tf.constant()创建张量

In [1]:
import tensorflow as tf
matrix1 = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix1)

C:\Users\Administrator\anaconda3\envs\DeepLearning-py310\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [2]:
matrix1.shape

TensorShape([2, 3])

In [3]:
matrix1.dtype

tf.int32

In [4]:
matrix1[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [5]:
print(matrix1 + 10)

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


In [6]:
# 开平方
print(tf.square(matrix1))

tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)


In [7]:
# 计算矩阵与自身转置的乘法 @是python里面的矩阵乘法运算符
print(matrix1 @ tf.transpose(matrix1))

tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [8]:
import tensorflow as tf
print(tf.__version__)

2.10.0
